# ------------------------------
# Training Configuration
# ------------------------------
experiment:
  name: "classification_experiment"
  seed: 42
  use_gpu: true

paths:
  train_images: "data/raw/seg_train/seg_train/"
  test_images: "data/raw/seg_test/seg_test/"
  model_save: "models/"
  logs: "outputs/logs/"

data:
  batch_size: 16
  image_size: 224        # Standard for ResNet
  val_split: 0.2
  num_workers: 2
  augmentations: true

model:
  name: "unet"       # OR resnet34
  in_channels: 3
  num_classes: 6         # buildings, forest, glacier, mountain, sea, street

training:
  epochs: 30
  learning_rate: 0.0001
  weight_decay: 0.0001
  optimizer: "adam"